### PR TITLE
Advise how to fix

### PR DESCRIPTION
**Pull request by ahmed-taj**
Before:

> There were the following issues with this Pull Request
> * Commit: de1c17986d9ba6abb5b1f2e28b4513e539c2df86
>    - ✖ message may not be empty
>    - ✖ type may not be empty
> * Commit: 698b7c9e5c7bba4d55403d2ff03769cfa0efc00f
>    - ✖ type may not be empty

After:
> There were the following issues with this Pull Request
> * Commit: de1c17986d9ba6abb5b1f2e28b4513e539c2df86
>    - ✖ message may not be empty
>    - ✖ type may not be empty
> * Commit: 698b7c9e5c7bba4d55403d2ff03769cfa0efc00f
>    - ✖ type may not be empty
> 
> You may need to [change the commit messages](https://help.github.com/articles/changing-a-commit-message/) to comply with the repository contributing guidelines.
> 
> --------
> 
> :robot:  This comment is autogenerated. If you noticed some issues please report them [here](https://github.com/ahmed-taj/commitlint-bot). Happy coding!

I only provided a hint for how to actually change commit message. I think the best place to know how to write correct commit messages should be the repository contributing guidelines.

### CODE REVIEW

**Comment by JasonEtco** [comment]
This looks great! 🎉 So glad you've found a way to help users correct their commit messages.

The only note I would give you is to also link to the repository's contributing guidelines, if possible. You can use the API to check if they have one, in the root of the repo or in the `.github` folder. That is, if you've enabled the "Read repo contents" permission - if you haven't, that's fine, it's just a nice touch :P

Also, you might as well use that footer message to point them to the app's repo; if people need to, they can learn a bit more about why its doing what its doing.

**Comment by ahmed-taj** [comment]
Thanks @JasonEtco for the quick response :+1: 

> Also, you might as well use that footer message to point them to the app's repo

Isn't the footer message actually points to the app's repo?

**Comment by JasonEtco** [comment]
> Isn't the footer message actually points to the app's repo?

Yep! But I meant you could say something like:

>  🤖  This comment was generated by [**commitlint[bot]**](https://github.com/ahmed-taj/commitlint-bot). Please report issues [here](https://github.com/ahmed-taj/commitlint-bot/issues). Happy coding!

**Comment by ahmed-taj** [comment]
Oh, that looks shorter and awesome :heart:

**Comment by JasonEtco** [comment]
@ahmed-taj cool! Also note that the second link points to `/issues`, just to be a little more specific ✨

**Comment by ahmed-taj** [comment]
I don't have `Read repo contents` permission enabled, so I will skip linking to the repository contributing guidelines for now ;)

**Pull request merged**
