### PR TITLE
fix: improve message

### PR DESCRIPTION
**Pull request by caarlos0**
refs https://github.com/z0al/commitlint-bot/issues/7

### CODE REVIEW

**Comment by caarlos0** [comment]
gently cc/ @z0al :D

**Comment by caarlos0** [comment]
it will look like this:

image

**Comment by z0al** [comment]
Hey @caarlos0, great work :sparkles: , thanks.

I've been able to touch this repo in a while, I will review this ASAP

P.S. I'm a big fan of your OSS work, keep it up.

**Comment by caarlos0** [comment]
Thanks @z0al :D 

I'm not used to write js and stuff, let me know if I did something wrong or not in the best way :) 

I did run the tests and deployed it to heroku - and both worked, so... there is that at least haha

Cheers

**Comment by z0al** [comment]
Merged https://github.com/z0al/commitlint-bot/commit/413a39b6a613925df67046e74deeee590557d87b

> I'm not used to write js and stuff, let me know if I did something wrong or not in the best way :)

Hahah, I wrote this 2 years ago while learning JS so my code isn't perfect either :D 

**Note:** Please keep in mind that these changes won't show up yet since I'm currently having a fight to deploy this to Now 2.0 and probably need to upgrade the code to a recent Probot version. 

Thank you.

**Pull request closed without merging**
